### ISSUE TITLE
Providing a script to preprocess text file(s) and output term/definition pairs.

### ISSUE THREAD

**Issue by aindilis** [DFKI-NLP/defx#1]
This looks very useful, I was able to build the model, however I haven't figured out how to have a script take unformatted text file(s) (not belonging to the DEFT corpus), and preprocess them, run the model and output terms and their definitions - if that is even possible.  That would be very useful.  I saw the prediction_analysis notebook, and thought that maybe that would contain enough information to write the script I am looking for, but was unable to figure it out (since I don't know Python or Jupyter).  (My use-case for definition extraction is (mathematical) knowledge management and intelligent tutoring systems - trying to populate a concept ontology).  Thanks!

**Comment by marchbnr** [comment]
Hello and thank you for your interest in our implementation!
I have to admit that there currently is no straightforward way to apply the model for an application. If you have already trained a model you could try to run the [demo](https://github.com/DFKI-NLP/defx/blob/master/streamlit_demo.py), as described in the [readme](https://github.com/DFKI-NLP/defx#running-a-demo).
If you run into troubles, post it here. I will keep this issue open in the meantime.

**Comment by aindilis** [comment]
Thank you for the feedback!  I managed to write something in Python using the streamlit demo which exports the results in JSON, but doesn't do error handling yet (can't timeout on bad input).  Note I currently do not know how to terminate the streamlit after extraction is finished.  (I then wrote some Perl scripts for extracting the JSON into more digestible lossy summarizations, and converted them into input suitable for the Cyc AI system (using ```(cyc-assert '(#$comment #$<TERM> "<DEF>") #$<MT>))```).  

I got promising results by processing this document: https://en.wikipedia.org/wiki/Boolean_satisfiability_problem
e.g.:

```(f "BooleanSatisfiabilityProblem-Defx")                                                                                                                                                                                                                                                                                    
(a '(#$comment #$BooleanSatisfiabilityProblem-Defx "Defx definition: problem of determining if there exists an interpretation that satisfies a given Boolean formula") #$MKMMt)```

Thanks again for the help.  Here is the Python in case you're interested:

```import sys

import streamlit as st
from allennlp.predictors import Predictor
import spacy
# from spacy import displacy                                                                                                                                                                                                                                                                                                   

import defx
from defx.util.displacy_formatter import DisplacyFormatter

import pprint
from pysbd.utils import PySBDFactory

model_name = sys.argv[1] or 'data/runs/joint_bert_classifier/model.tar.gz'
print('Loading model from', model_name)


def setup_predictor():
    pred = Predictor.from_path(model_name, 'joint-classifier')
    return pred


predictor = st.cache(
    setup_predictor,
    allow_output_mutation=True  # the Predictor is not hashable                                                                                                                                                                                                                                                                
)()

st.title('Defx demo')

with open('/tmp/defx-input.txt') as x: f = x.read()

nlp = spacy.blank('en')
nlp.add_pipe(PySBDFactory(nlp))
doc = nlp(f)

output = list();

for sent in list(doc.sents):
    text = st.text_input("Model input", sent)
    result = predictor.predict_json({'sentence': text})
    output.append({"tags" : result['tags'], "words" : result['words']})

with open("/tmp/defx-output.json", "w") as fout:
    fout.write(pprint.pformat({"results" : output}))
```

**Comment by marchbnr** [comment]
I am happy, that I could help you. Actually you could just remove streamlit, since you do not use the web interface. Create the predictor without using the streamlit cache, like this:
`predictor = Predictor.from_path(model_name, 'joint-classifier')`
Then you can delete the streamlit import statement and all references to it (st.*).
